// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: knx/groupaddress/v1/groupaddressservice.proto

package v1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/genproto/googleapis/api/visibility"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event int32

const (
	Event_EVENT_UNSPECIFIED Event = 0
	Event_EVENT_READ        Event = 1
	Event_EVENT_RESPONSE    Event = 2
	Event_EVENT_WRITE       Event = 3
)

// Enum value maps for Event.
var (
	Event_name = map[int32]string{
		0: "EVENT_UNSPECIFIED",
		1: "EVENT_READ",
		2: "EVENT_RESPONSE",
		3: "EVENT_WRITE",
	}
	Event_value = map[string]int32{
		"EVENT_UNSPECIFIED": 0,
		"EVENT_READ":        1,
		"EVENT_RESPONSE":    2,
		"EVENT_WRITE":       3,
	}
)

func (x Event) Enum() *Event {
	p := new(Event)
	*p = x
	return p
}

func (x Event) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Event) Descriptor() protoreflect.EnumDescriptor {
	return file_knx_groupaddress_v1_groupaddressservice_proto_enumTypes[0].Descriptor()
}

func (Event) Type() protoreflect.EnumType {
	return &file_knx_groupaddress_v1_groupaddressservice_proto_enumTypes[0]
}

func (x Event) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Event.Descriptor instead.
func (Event) EnumDescriptor() ([]byte, []int) {
	return file_knx_groupaddress_v1_groupaddressservice_proto_rawDescGZIP(), []int{0}
}

type PublishRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// group_address to target the message to, required
	// valid format: 1/2/3
	GroupAddress string `protobuf:"bytes,1,opt,name=group_address,json=groupAddress,proto3" json:"group_address,omitempty"`
	// physical_address to be used when writing to the bus, optional
	// valid format: 1.2.3
	PhysicalAddress string `protobuf:"bytes,2,opt,name=physical_address,json=physicalAddress,proto3" json:"physical_address,omitempty"`
	// type of bus message, optional (defaults to EVENT_WRITE)
	Event Event `protobuf:"varint,3,opt,name=event,proto3,enum=knx.groupaddress.v1.Event" json:"event,omitempty"`
	// actual data to write to the bus, required for EVENT_WRITE
	Data          []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_knx_groupaddress_v1_groupaddressservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knx_groupaddress_v1_groupaddressservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_knx_groupaddress_v1_groupaddressservice_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetGroupAddress() string {
	if x != nil {
		return x.GroupAddress
	}
	return ""
}

func (x *PublishRequest) GetPhysicalAddress() string {
	if x != nil {
		return x.PhysicalAddress
	}
	return ""
}

func (x *PublishRequest) GetEvent() Event {
	if x != nil {
		return x.Event
	}
	return Event_EVENT_UNSPECIFIED
}

func (x *PublishRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_knx_groupaddress_v1_groupaddressservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knx_groupaddress_v1_groupaddressservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_knx_groupaddress_v1_groupaddressservice_proto_rawDescGZIP(), []int{1}
}

type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// group_addresses to subscribe to, optional (defaults to any group_adresses)
	// valid format: 1/2/3
	GroupAddresses []string `protobuf:"bytes,1,rep,name=group_addresses,json=groupAddresses,proto3" json:"group_addresses,omitempty"`
	// events to subscribe to, optional (defaults to EVENT_UNSPECIFIED meaning any)
	Event         Event `protobuf:"varint,2,opt,name=event,proto3,enum=knx.groupaddress.v1.Event" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_knx_groupaddress_v1_groupaddressservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knx_groupaddress_v1_groupaddressservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_knx_groupaddress_v1_groupaddressservice_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetGroupAddresses() []string {
	if x != nil {
		return x.GroupAddresses
	}
	return nil
}

func (x *SubscribeRequest) GetEvent() Event {
	if x != nil {
		return x.Event
	}
	return Event_EVENT_UNSPECIFIED
}

type SubscribeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GroupAddress    string                 `protobuf:"bytes,1,opt,name=group_address,json=groupAddress,proto3" json:"group_address,omitempty"`
	PhysicalAddress string                 `protobuf:"bytes,2,opt,name=physical_address,json=physicalAddress,proto3" json:"physical_address,omitempty"`
	Event           Event                  `protobuf:"varint,3,opt,name=event,proto3,enum=knx.groupaddress.v1.Event" json:"event,omitempty"`
	Data            []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_knx_groupaddress_v1_groupaddressservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knx_groupaddress_v1_groupaddressservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_knx_groupaddress_v1_groupaddressservice_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeResponse) GetGroupAddress() string {
	if x != nil {
		return x.GroupAddress
	}
	return ""
}

func (x *SubscribeResponse) GetPhysicalAddress() string {
	if x != nil {
		return x.PhysicalAddress
	}
	return ""
}

func (x *SubscribeResponse) GetEvent() Event {
	if x != nil {
		return x.Event
	}
	return Event_EVENT_UNSPECIFIED
}

func (x *SubscribeResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SubscribeUnaryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// wrapped SubscribeRequest
	SubscribeRequest *SubscribeRequest `protobuf:"bytes,1,opt,name=subscribe_request,json=subscribeRequest,proto3" json:"subscribe_request,omitempty"`
	// suscribe for this duration string, optional (if missing, will wait and return the first message)
	For           string `protobuf:"bytes,3,opt,name=for,proto3" json:"for,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeUnaryRequest) Reset() {
	*x = SubscribeUnaryRequest{}
	mi := &file_knx_groupaddress_v1_groupaddressservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeUnaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeUnaryRequest) ProtoMessage() {}

func (x *SubscribeUnaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knx_groupaddress_v1_groupaddressservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeUnaryRequest.ProtoReflect.Descriptor instead.
func (*SubscribeUnaryRequest) Descriptor() ([]byte, []int) {
	return file_knx_groupaddress_v1_groupaddressservice_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeUnaryRequest) GetSubscribeRequest() *SubscribeRequest {
	if x != nil {
		return x.SubscribeRequest
	}
	return nil
}

func (x *SubscribeUnaryRequest) GetFor() string {
	if x != nil {
		return x.For
	}
	return ""
}

type SubscribeUnaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*SubscribeResponse   `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeUnaryResponse) Reset() {
	*x = SubscribeUnaryResponse{}
	mi := &file_knx_groupaddress_v1_groupaddressservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeUnaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeUnaryResponse) ProtoMessage() {}

func (x *SubscribeUnaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knx_groupaddress_v1_groupaddressservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeUnaryResponse.ProtoReflect.Descriptor instead.
func (*SubscribeUnaryResponse) Descriptor() ([]byte, []int) {
	return file_knx_groupaddress_v1_groupaddressservice_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeUnaryResponse) GetMessages() []*SubscribeResponse {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_knx_groupaddress_v1_groupaddressservice_proto protoreflect.FileDescriptor

const file_knx_groupaddress_v1_groupaddressservice_proto_rawDesc = "" +
	"\n" +
	"-knx/groupaddress/v1/groupaddressservice.proto\x12\x13knx.groupaddress.v1\x1a\x1bgoogle/api/visibility.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xa2\x02\n" +
	"\x0ePublishRequest\x12(\n" +
	"\rgroup_address\x18\x01 \x01(\tB\x03\xe0A\x02R\fgroupAddress\x12.\n" +
	"\x10physical_address\x18\x02 \x01(\tB\x03\xe0A\x01R\x0fphysicalAddress\x125\n" +
	"\x05event\x18\x03 \x01(\x0e2\x1a.knx.groupaddress.v1.EventB\x03\xe0A\x01R\x05event\x12\x17\n" +
	"\x04data\x18\x04 \x01(\fB\x03\xe0A\x01R\x04data:f\x92Ac2a{ \"group_address\": \"1/2/3\", \"physical_address\": \"0.0.0\", \"event\": \"EVENT_WRITE\", \"data\": \"AQo=\" }\"\x11\n" +
	"\x0fPublishResponse\"\xc5\x01\n" +
	"\x10SubscribeRequest\x12,\n" +
	"\x0fgroup_addresses\x18\x01 \x03(\tB\x03\xe0A\x01R\x0egroupAddresses\x125\n" +
	"\x05event\x18\x02 \x01(\x0e2\x1a.knx.groupaddress.v1.EventB\x03\xe0A\x01R\x05event:L\x92AI2G{ \"group_addresses\": [\"1/2/3\", \"4/5/6\"], \"event\": \"EVENT_UNSPECIFIED\" }\"\xa9\x01\n" +
	"\x11SubscribeResponse\x12#\n" +
	"\rgroup_address\x18\x01 \x01(\tR\fgroupAddress\x12)\n" +
	"\x10physical_address\x18\x02 \x01(\tR\x0fphysicalAddress\x120\n" +
	"\x05event\x18\x03 \x01(\x0e2\x1a.knx.groupaddress.v1.EventR\x05event\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\x97\x02\n" +
	"\x15SubscribeUnaryRequest\x12W\n" +
	"\x11subscribe_request\x18\x01 \x01(\v2%.knx.groupaddress.v1.SubscribeRequestB\x03\xe0A\x01R\x10subscribeRequest\x12\x15\n" +
	"\x03for\x18\x03 \x01(\tB\x03\xe0A\x01R\x03for:\x8d\x01\x92A\x89\x012\x86\x01{\"subscribe_request\": { \"group_address\": \"1/2/3\", \"physical_address\": \"0.0.0\", \"event\": \"EVENT_WRITE\", \"data\": \"AQo=\" }, \"for\": \"10s\"}\"\\\n" +
	"\x16SubscribeUnaryResponse\x12B\n" +
	"\bmessages\x18\x01 \x03(\v2&.knx.groupaddress.v1.SubscribeResponseR\bmessages*S\n" +
	"\x05Event\x12\x15\n" +
	"\x11EVENT_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"EVENT_READ\x10\x01\x12\x12\n" +
	"\x0eEVENT_RESPONSE\x10\x02\x12\x0f\n" +
	"\vEVENT_WRITE\x10\x032\xd8\x02\n" +
	"\x13GroupAddressService\x12V\n" +
	"\aPublish\x12#.knx.groupaddress.v1.PublishRequest\x1a$.knx.groupaddress.v1.PublishResponse\"\x00\x12^\n" +
	"\tSubscribe\x12%.knx.groupaddress.v1.SubscribeRequest\x1a&.knx.groupaddress.v1.SubscribeResponse\"\x000\x01\x12w\n" +
	"\x0eSubscribeUnary\x12*.knx.groupaddress.v1.SubscribeUnaryRequest\x1a+.knx.groupaddress.v1.SubscribeUnaryResponse\"\f\xfa\xd2\xe4\x93\x02\x06\x12\x04BETA\x1a\x10\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bRELEASEDB\x8d\x02\x92A\xdb\x01\x12z\n" +
	"\x17KNX GroupAddressService\"L\n" +
	"\x12Christoph Hoopmann\x12!https://github.com/choopm/knxrpc/\x1a\x13choopm@0pointer.org*\f\n" +
	"\n" +
	"Apache-2.02\x030.1*\x02\x01\x022\x10application/json:\x10application/jsonZ#\n" +
	"!\n" +
	"\n" +
	"ApiKeyAuth\x12\x13\b\x02\x1a\rAuthorization \x02b\x10\n" +
	"\x0e\n" +
	"\n" +
	"ApiKeyAuth\x12\x00Z,github.com/choopm/knxrpc/knx/groupaddress/v1b\x06proto3"

var (
	file_knx_groupaddress_v1_groupaddressservice_proto_rawDescOnce sync.Once
	file_knx_groupaddress_v1_groupaddressservice_proto_rawDescData []byte
)

func file_knx_groupaddress_v1_groupaddressservice_proto_rawDescGZIP() []byte {
	file_knx_groupaddress_v1_groupaddressservice_proto_rawDescOnce.Do(func() {
		file_knx_groupaddress_v1_groupaddressservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_knx_groupaddress_v1_groupaddressservice_proto_rawDesc), len(file_knx_groupaddress_v1_groupaddressservice_proto_rawDesc)))
	})
	return file_knx_groupaddress_v1_groupaddressservice_proto_rawDescData
}

var file_knx_groupaddress_v1_groupaddressservice_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_knx_groupaddress_v1_groupaddressservice_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_knx_groupaddress_v1_groupaddressservice_proto_goTypes = []any{
	(Event)(0),                     // 0: knx.groupaddress.v1.Event
	(*PublishRequest)(nil),         // 1: knx.groupaddress.v1.PublishRequest
	(*PublishResponse)(nil),        // 2: knx.groupaddress.v1.PublishResponse
	(*SubscribeRequest)(nil),       // 3: knx.groupaddress.v1.SubscribeRequest
	(*SubscribeResponse)(nil),      // 4: knx.groupaddress.v1.SubscribeResponse
	(*SubscribeUnaryRequest)(nil),  // 5: knx.groupaddress.v1.SubscribeUnaryRequest
	(*SubscribeUnaryResponse)(nil), // 6: knx.groupaddress.v1.SubscribeUnaryResponse
}
var file_knx_groupaddress_v1_groupaddressservice_proto_depIdxs = []int32{
	0, // 0: knx.groupaddress.v1.PublishRequest.event:type_name -> knx.groupaddress.v1.Event
	0, // 1: knx.groupaddress.v1.SubscribeRequest.event:type_name -> knx.groupaddress.v1.Event
	0, // 2: knx.groupaddress.v1.SubscribeResponse.event:type_name -> knx.groupaddress.v1.Event
	3, // 3: knx.groupaddress.v1.SubscribeUnaryRequest.subscribe_request:type_name -> knx.groupaddress.v1.SubscribeRequest
	4, // 4: knx.groupaddress.v1.SubscribeUnaryResponse.messages:type_name -> knx.groupaddress.v1.SubscribeResponse
	1, // 5: knx.groupaddress.v1.GroupAddressService.Publish:input_type -> knx.groupaddress.v1.PublishRequest
	3, // 6: knx.groupaddress.v1.GroupAddressService.Subscribe:input_type -> knx.groupaddress.v1.SubscribeRequest
	5, // 7: knx.groupaddress.v1.GroupAddressService.SubscribeUnary:input_type -> knx.groupaddress.v1.SubscribeUnaryRequest
	2, // 8: knx.groupaddress.v1.GroupAddressService.Publish:output_type -> knx.groupaddress.v1.PublishResponse
	4, // 9: knx.groupaddress.v1.GroupAddressService.Subscribe:output_type -> knx.groupaddress.v1.SubscribeResponse
	6, // 10: knx.groupaddress.v1.GroupAddressService.SubscribeUnary:output_type -> knx.groupaddress.v1.SubscribeUnaryResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_knx_groupaddress_v1_groupaddressservice_proto_init() }
func file_knx_groupaddress_v1_groupaddressservice_proto_init() {
	if File_knx_groupaddress_v1_groupaddressservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_knx_groupaddress_v1_groupaddressservice_proto_rawDesc), len(file_knx_groupaddress_v1_groupaddressservice_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_knx_groupaddress_v1_groupaddressservice_proto_goTypes,
		DependencyIndexes: file_knx_groupaddress_v1_groupaddressservice_proto_depIdxs,
		EnumInfos:         file_knx_groupaddress_v1_groupaddressservice_proto_enumTypes,
		MessageInfos:      file_knx_groupaddress_v1_groupaddressservice_proto_msgTypes,
	}.Build()
	File_knx_groupaddress_v1_groupaddressservice_proto = out.File
	file_knx_groupaddress_v1_groupaddressservice_proto_goTypes = nil
	file_knx_groupaddress_v1_groupaddressservice_proto_depIdxs = nil
}
